baseurl = "http://vietch2612.github.io/qablog/"
title = "Cao Hoai Viet Blog"
languageCode = "en-us"
disqusShortname = "hoaiviet" # Optional, enable Disqus integration
MetaDataFormat = "hyde"
theme = "hyde"
paginate = 15

[author]
    name = "Hoai Viet"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = true

    # Used when a given page doesn't set its own.
    defaultDescription = "Share more to Learn more"
    defaultKeywords = "automation,qa,quality,testing"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-00"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "monokai"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Senior Automation QA at Silicon Straits Saigon"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Blog"

    # Metadata used to drive integrations.
    googleAuthorship = "viet.ch2612"
    googleAnalytics = "Your Google Analytics tracking code"
    gravatarHash = "MD5 hash of your Gravatar email address"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/vietch2612"
    bitbucket = ""
    stackOverflow = ""
    linkedin = "https://vn.linkedin.com/in/vietch2612"
    googleplus = ""
    facebook = ""
    twitter = ""
    youtube = ""

    # Other social-like sidebar links
    rss = false  # switch to true to enable RSS icon link
    flattr = ""  # populate with your flattr uid
